name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  LIBRESPOT_VERSION: 1.6.3
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Fetch configured JAR
      run: curl -O -L https://github.com/librespot-org/librespot-java/releases/download/v${LIBRESPOT_VERSION}/librespot-player-${LIBRESPOT_VERSION}.jar
    
    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.REGISTRY }}/yostinso/librespot-java:${{ env.LIBRESPOT_VERSION }},${{ env.REGISTRY }}/yostinso/librespot-java:latest
        build-args: LIBRESPOT_JAR=librespot-player-${{ env.LIBRESPOT_VERSION }}.jar
